// Structure des catégories / sous-catégories + poses de base (banque de départ).
// Ce contenu est un point de départ : Victor complète avec ses propres photos via "+ Ajouter".
// Chaque pose porte un champ focal:[min,max] (en mm) utilisé pour la comparaison avec le matériel déclaré.

const CATEGORIES = [
  {
    id: "mariage",
    label: "Mariage",
    icon: "rings",
    subcategories: [
      { id: "preparatifs", label: "Préparatifs" },
      { id: "ceremonie", label: "Cérémonie" },
      { id: "portraits-couple", label: "Portraits de couple" },
      { id: "groupe", label: "Photos de groupe" },
      { id: "cocktail", label: "Cocktail" },
      { id: "soiree", label: "Soirée" }
    ]
  },
  {
    id: "couple",
    label: "Couple",
    icon: "heart",
    subcategories: [
      { id: "classiques", label: "Poses classiques" },
      { id: "mouvement", label: "En mouvement" },
      { id: "proches", label: "Assis / proches" },
      { id: "details", label: "Gros plans / détails" }
    ]
  },
  {
    id: "famille",
    label: "Famille",
    icon: "people",
    subcategories: [
      { id: "multigen", label: "Groupe multigénérationnel" },
      { id: "enfants", label: "Enfants" },
      { id: "parent-enfant", label: "Duo parent-enfant" },
      { id: "individuel", label: "Portraits individuels" },
      { id: "maman-enfant", label: "Maman avec bébé / enfant" },
      { id: "papa-enfant", label: "Papa avec bébé / enfant" }
    ]
  },
  {
    id: "corporate",
    label: "Corporate",
    icon: "briefcase",
    subcategories: [
      { id: "trombinoscope", label: "Portraits / trombinoscope" },
      { id: "atelier", label: "Ambiance travail / atelier" },
      { id: "equipe", label: "Groupe équipe" },
      { id: "networking", label: "Networking" }
    ]
  },
  {
    id: "solo",
    label: "Personne seule",
    icon: "soloperson",
    subcategories: [
      { id: "femme", label: "Femme" },
      { id: "homme", label: "Homme" }
    ]
  }
];

const SEED_POSES = [
  // --- MARIAGE / Préparatifs
  { cat: "mariage", sub: "preparatifs", name: "Détails posés", photo: "https://images.unsplash.com/photo-1734578998441-8fab204d5b68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Alliances, bouquet, parfum, chaussures posés sur un fond texturé (lit, rebord de fenêtre).", technique: "50mm ou 35mm, f/2.8-f/4, lumière naturelle douce, mise au point macro si possible.", focal: [35, 50] },
  { cat: "mariage", sub: "preparatifs", name: "Enfilage de la robe / dernier bouton", photo: "https://images.unsplash.com/photo-1600287792237-3f66db635a73?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se placer derrière ou sur le côté, demander aux proches de continuer naturellement sans regarder l'objectif.", technique: "70-200mm à distance pour rester discret, f/2.8, priorité au visage net.", focal: [70, 200] },
  { cat: "mariage", sub: "preparatifs", name: "Regard dans le miroir", photo: "https://images.unsplash.com/photo-1640654526083-a2287673acce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Cadrer le reflet + le sujet, demander un léger sourire ou un regard pensif vers le miroir.", technique: "35-50mm, attention à ne pas se refléter soi-même, f/2.2.", focal: [35, 50] },
  { cat: "mariage", sub: "preparatifs", name: "Rires entre amies", photo: "https://images.unsplash.com/photo-1749096290813-5bd0bfa96364?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Demoiselles d'honneur qui aident aux derniers préparatifs, capter un rire complice et spontané.", technique: "35-50mm, f/2.8, rester en retrait pour ne pas figer la scène.", focal: [35, 50] },
  { cat: "mariage", sub: "preparatifs", name: "Boutonnière / nœud papillon", photo: "https://images.unsplash.com/photo-1708133301406-ca473e05b035?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Le marié ajuste sa cravate ou son nœud papillon, cadrer serré sur les mains et le col.", technique: "50mm, f/2, mise au point sur les doigts.", focal: [50, 50] },
  { cat: "mariage", sub: "preparatifs", name: "Dernier regard avant de partir", photo: "https://images.unsplash.com/photo-1652881389205-9f85f82888c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Sujet seul face à un miroir ou une fenêtre, instant de calme juste avant de rejoindre la cérémonie.", technique: "85mm, f/2, lumière douce et diffuse.", focal: [85, 85] },

  // --- MARIAGE / Cérémonie
  { cat: "mariage", sub: "ceremonie", name: "Entrée / arrivée", photo: "https://images.unsplash.com/photo-1660775444627-b432f34bd72e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se positionner en angle (jamais pile dans l'axe) pour capter l'émotion des visages qui se tournent.", technique: "70-200mm, mode silencieux/rideau électronique, f/4 pour profondeur de champ de sécurité.", focal: [70, 200] },
  { cat: "mariage", sub: "ceremonie", name: "Échange des vœux / alliances", photo: "https://images.unsplash.com/photo-1672288304335-aa4de39ddb13?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se rapprocher discrètement, viser le contact visuel entre les mariés et les mains au moment de l'échange.", technique: "70-200mm à f/2.8, rafale courte pour ne pas louper le geste.", focal: [70, 200] },
  { cat: "mariage", sub: "ceremonie", name: "Premier baiser", photo: "https://images.unsplash.com/photo-1517617823475-013756831d1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Anticiper le signal (officiant), se placer légèrement de côté pour éviter les dos qui cachent la scène.", technique: "70-200mm, vitesse mini 1/500e, rafale.", focal: [70, 200] },
  { cat: "mariage", sub: "ceremonie", name: "Signature du registre", photo: "https://images.unsplash.com/photo-1724404853530-a19ff2ed3c4b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Gros plan sur la main qui signe, alliance visible, capter la concentration du geste.", technique: "50-85mm, f/2.8, mise au point sur le stylo/la main.", focal: [50, 85] },
  { cat: "mariage", sub: "ceremonie", name: "Larme d'émotion d'un proche", photo: "https://images.unsplash.com/photo-1788462809866-82a2e99dc9ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Scanner discrètement l'assemblée pendant la cérémonie, viser un visage ému sans le déranger.", technique: "70-200mm, f/2.8, discrétion maximale.", focal: [70, 200] },
  { cat: "mariage", sub: "ceremonie", name: "Sortie sous les applaudissements", photo: "https://images.unsplash.com/photo-1758810409971-a5e93f7a4f98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se placer en bout d'allée pour capter le mouvement des pétales/riz lancés et les applaudissements.", technique: "24-70mm, f/4, rafale au moment du lancer.", focal: [24, 70] },

  // --- MARIAGE / Portraits de couple
  { cat: "mariage", sub: "portraits-couple", name: "Front contre front", photo: "https://images.unsplash.com/photo-1752222256785-be9635a75f98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "\"Rapprochez vos fronts, fermez les yeux, respirez\" — capter juste avant/après un sourire spontané.", technique: "85mm, f/1.8-2.2, contre-jour ou lumière rasante en fin de journée.", focal: [85, 85] },
  { cat: "mariage", sub: "portraits-couple", name: "Marche vers l'objectif, mains liées", photo: "https://images.unsplash.com/photo-1707191585140-fe1d745a9e6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "\"Marchez naturellement en discutant, je vous suis\" — plusieurs passages, ne pas regarder l'objectif au début.", technique: "35-50mm, suivi en marchant, f/2.8 pour garder les deux nets.", focal: [35, 50] },
  { cat: "mariage", sub: "portraits-couple", name: "Danse improvisée / tour", photo: "https://images.unsplash.com/photo-1648154164366-d067faecdc51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Faire tourner la mariée d'un mouvement lent, capter le mouvement de la robe/du voile.", technique: "50-85mm, vitesse 1/250e mini pour figer, ou 1/60e pour filé volontaire.", focal: [50, 85] },
  { cat: "mariage", sub: "portraits-couple", name: "Silhouette contre-jour", photo: "https://images.unsplash.com/photo-1542460533-50ac46fb13d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se placer face au soleil bas, couple en profil ou de dos, corps légèrement décalés pour se distinguer.", technique: "50-85mm, exposition sur le ciel, f/4-5.6, spot lumineux type golden hour.", focal: [50, 85] },
  { cat: "mariage", sub: "portraits-couple", name: "Sous un arbre / voûte florale", photo: "https://images.unsplash.com/photo-1774625068161-e56a038bdba8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Couple enlacé sous un élément naturel (arbre, arche fleurie), lumière tamisée par le feuillage.", technique: "50-85mm, f/2, exploiter les taches de lumière en arrière-plan.", focal: [50, 85] },
  { cat: "mariage", sub: "portraits-couple", name: "Reflet dans l'eau ou une vitre", photo: "https://images.unsplash.com/photo-1774814329688-613bae459b88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Jouer avec un reflet (flaque, fenêtre, miroir d'eau) pour doubler la composition.", technique: "35-50mm, f/4, cadrer pour inclure le reflet net.", focal: [35, 50] },
  { cat: "mariage", sub: "portraits-couple", name: "Nez à nez, rire partagé", photo: "https://images.unsplash.com/photo-1759904529526-d17339f7bd43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Fronts proches, demander une petite blague pour provoquer un rire vrai et spontané.", technique: "85mm, f/1.8, rafale courte au moment du rire.", focal: [85, 85] },

  // --- MARIAGE / Photos de groupe
  { cat: "mariage", sub: "groupe", name: "Grand groupe pyramidal", photo: "https://images.unsplash.com/photo-1695719416493-95257680511f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Petits devant assis, moyens debout, grands au fond légèrement décalés — jamais tous alignés à la même hauteur.", technique: "24-35mm à bonne distance, f/5.6-f/8 pour la profondeur de champ, flash de débouchage si contre-jour.", focal: [24, 35] },
  { cat: "mariage", sub: "groupe", name: "Lancer / saut collectif", photo: "https://images.unsplash.com/photo-1750187176449-403f300462a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Compte à rebours annoncé à voix haute (\"3-2-1 sautez !\"), rafale déclenchée juste avant le \"1\".", technique: "24-35mm, vitesse 1/1000e mini, rafale haute cadence.", focal: [24, 35] },
  { cat: "mariage", sub: "groupe", name: "Groupe rapproché rieur", photo: "https://images.unsplash.com/photo-1749062238703-83f7ce3e6d44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Serrer le groupe, demander une blague ou un \"dites plus fort que le voisin je vous entends pas !\" pour un rire naturel.", technique: "35-50mm, f/4, plusieurs déclenchements rapprochés.", focal: [35, 50] },
  { cat: "mariage", sub: "groupe", name: "Groupe des témoins", photo: "https://images.unsplash.com/photo-1640654500004-501c41c85e32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Témoins/demoiselles disposés en léger arc, mettre en valeur bouquets ou accessoires assortis.", technique: "35mm, f/4, distance suffisante pour tous les inclure.", focal: [35, 35] },
  { cat: "mariage", sub: "groupe", name: "Photo depuis un point haut", photo: "https://images.unsplash.com/photo-1781355480278-b2ce53e5dae1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se placer sur un balcon ou des marches, demander à tout le monde de lever la tête vers l'objectif.", technique: "24mm, f/5.6, attention à la déformation en bord de cadre.", focal: [24, 24] },
  { cat: "mariage", sub: "groupe", name: "Génération par génération", photo: "https://images.unsplash.com/photo-1706200637521-b446bd05df0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Enchaîner rapidement les sous-groupes (amis, famille proche, famille élargie) sans casser le rythme.", technique: "35-50mm, f/5.6, garder la même position pour gagner du temps.", focal: [35, 50] },

  // --- MARIAGE / Cocktail
  { cat: "mariage", sub: "cocktail", name: "Discussion animée", photo: "https://images.unsplash.com/photo-1742890184672-3ac8f37095cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Rester en retrait, capter les échanges naturels sans diriger, privilégier les mains qui parlent et les regards croisés.", technique: "70-200mm, f/2.8-4, discrétion maximale, pas de flash direct.", focal: [70, 200] },
  { cat: "mariage", sub: "cocktail", name: "Trinquer / verre levé", photo: "https://images.unsplash.com/photo-1785744563469-9c1223bf2ebb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Repérer un groupe qui lève son verre, se placer avant le \"tchin\" pour capter le geste et les sourires.", technique: "35-50mm, f/2.8, rafale courte.", focal: [35, 50] },
  { cat: "mariage", sub: "cocktail", name: "Ambiance large + détails", photo: "https://images.unsplash.com/photo-1761114905078-163aa92141c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Alterner plan large du lieu/déco et gros plans (petits fours, decoration de table) pour varier le rythme du récit.", technique: "24mm pour le large, 50mm pour les détails.", focal: [24, 50] },
  { cat: "mariage", sub: "cocktail", name: "Jeux d'extérieur / animation", photo: "https://images.unsplash.com/photo-1749320128113-10793ef5a82a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Pétanque, molkky ou autre animation, capter l'action et les rires des participants.", technique: "70-200mm, f/4, rafale au moment du geste.", focal: [70, 200] },
  { cat: "mariage", sub: "cocktail", name: "Service des boissons / buffet", photo: "https://images.unsplash.com/photo-1767469902391-6c20cbb2d80c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Moment convivial autour du bar ou du buffet, ambiance détendue et naturelle.", technique: "35-50mm, f/2.8, discrétion.", focal: [35, 50] },
  { cat: "mariage", sub: "cocktail", name: "Enfants qui jouent pendant le cocktail", photo: "https://images.unsplash.com/photo-1776412458113-123d077aab4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Profiter du moment libre des enfants en arrière-plan de la fête pour une touche spontanée.", technique: "50-85mm, f/2.8, mise au point sur l'expression du visage.", focal: [50, 85] },

  // --- MARIAGE / Soirée
  { cat: "mariage", sub: "soiree", name: "Ouverture de bal", photo: "https://images.unsplash.com/photo-1648154164366-d067faecdc51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Se placer en angle 3/4 face, jamais complètement de dos ni pile face, suivre les mariés dans leur mouvement.", technique: "24-70mm, f/2.8, ISO élevé (1600-6400), flash rebond si plafond blanc bas.", focal: [24, 70] },
  { cat: "mariage", sub: "soiree", name: "Dancefloor plein", photo: "https://images.unsplash.com/photo-1482575832494-771f74bf6857?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Capter le mouvement flou des danseurs autour d'un point net (les mariés), varier les angles bas/hauts.", technique: "24-35mm, vitesse lente 1/30e avec flash synchro pour filé + net (flash + rideau).", focal: [24, 35] },
  { cat: "mariage", sub: "soiree", name: "Pièce montée / gâteau", photo: "https://images.unsplash.com/photo-1686354715541-8fa88eee016d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Cadrer serré sur le geste de découpe, veiller à la lumière sur les visages des mariés penchés vers le gâteau.", technique: "35-50mm, f/2.8, flash rebond doux pour équilibrer l'ambiance.", focal: [35, 50] },
  { cat: "mariage", sub: "soiree", name: "Feu d'artifice / lanternes", photo: "https://images.unsplash.com/photo-1550713450-5f14c923ebd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Capter le ciel et les invités qui regardent vers le haut, jouer sur les lumières du ciel.", technique: "24mm, f/2.8, pose longue si trépied disponible.", focal: [24, 24] },
  { cat: "mariage", sub: "soiree", name: "Discours émouvant", photo: "https://images.unsplash.com/photo-1775126964395-6627fd47cabe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Orateur au micro, alterner avec les réactions des mariés et des invités.", technique: "70-200mm, f/2.8, ISO élevé en salle sombre.", focal: [70, 200] },
  { cat: "mariage", sub: "soiree", name: "Derniers danseurs / fin de soirée", photo: "https://images.unsplash.com/photo-1704564552265-c796d1d38f6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Ambiance tamisée, quelques couples encore sur la piste, capter la fatigue heureuse de la soirée.", technique: "35-50mm, f/2, ISO élevé.", focal: [35, 50] },

  // --- COUPLE / Poses classiques
  { cat: "couple", sub: "classiques", name: "Face à face, mains jointes", photo: "https://images.unsplash.com/photo-1541679368093-5c967ac6de11?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "\"Rapprochez-vous, prenez-vous les mains, regardez-vous\" — laisser un temps de silence pour un moment vrai.", technique: "85mm, f/1.8-2.5, lumière douce (ombre ou golden hour).", focal: [85, 85] },
  { cat: "couple", sub: "classiques", name: "Un partenaire porte l'autre sur le dos", photo: "https://images.unsplash.com/photo-1555689070-2d15336749b6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Demander de rire pendant le mouvement, capter juste après le déséquilibre/rire spontané.", technique: "35-50mm, vitesse 1/500e, rafale.", focal: [35, 50] },
  { cat: "couple", sub: "classiques", name: "Baiser sur le front", photo: "https://images.unsplash.com/photo-1540076156429-35ffe82b7870?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "L'un incline légèrement la tête, l'autre dépose un baiser — capter la texture des mains et le regard fermé.", technique: "85mm, f/2, cadrage serré poitrine.", focal: [85, 85] },
  { cat: "couple", sub: "classiques", name: "Enlacés de dos regardant l'horizon", photo: "https://images.unsplash.com/photo-1776893310146-98cdb22d0fac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Vue sur un paysage, couple de dos, têtes légèrement rapprochées.", technique: "35-50mm, f/4, privilégier un point de fuite clair.", focal: [35, 50] },
  { cat: "couple", sub: "classiques", name: "Front contre front debout", photo: "https://images.unsplash.com/photo-1763713512996-f4242212bc08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Debout en extérieur, fronts joints, yeux fermés, laisser un temps de silence.", technique: "85mm, f/2, lumière douce.", focal: [85, 85] },
  { cat: "couple", sub: "classiques", name: "Portrait à deux, sourire complice", photo: "https://images.unsplash.com/photo-1608145640433-937abd82a4e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Face caméra, épaule contre épaule, sourire naturel provoqué par une remarque.", technique: "50-85mm, f/2, mise au point sur les deux visages.", focal: [50, 85] },

  // --- COUPLE / En mouvement
  { cat: "couple", sub: "mouvement", name: "Marche main dans la main, dos à la caméra", photo: "https://images.unsplash.com/photo-1602039855133-b4d18d4c1d45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Les faire marcher loin devant, demander un regard échangé à mi-parcours.", technique: "35-50mm, f/4, suivre en marchant en arrière si sécurité du terrain le permet.", focal: [35, 50] },
  { cat: "couple", sub: "mouvement", name: "Course / rire complice", photo: "https://images.unsplash.com/photo-1719564320182-da145562ef46?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "\"Courez doucement en vous tenant la main en riant\" — répéter 2-3 fois pour un mouvement naturel.", technique: "50mm, vitesse 1/640e mini, mode continu AF.", focal: [50, 50] },
  { cat: "couple", sub: "mouvement", name: "Tourner sur soi / robe qui vole", photo: "https://images.unsplash.com/photo-1781145611306-d15c0bb652e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Faire tourner lentement puis accélérer, déclencher au moment du mouvement le plus ample.", technique: "50-85mm, 1/500e, rafale haute cadence.", focal: [50, 85] },
  { cat: "couple", sub: "mouvement", name: "Saut synchronisé", photo: "https://images.unsplash.com/photo-1721199980955-bc86c0ee9c0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Sauter ensemble en riant, compter à voix haute, déclencher juste avant le point culminant.", technique: "35-50mm, vitesse 1/1000e mini.", focal: [35, 50] },
  { cat: "couple", sub: "mouvement", name: "Danse improvisée en extérieur", photo: "https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Un mouvement de valse ou un tour dansé en plein air, capter la complicité en action.", technique: "50-85mm, 1/500e, rafale.", focal: [50, 85] },
  { cat: "couple", sub: "mouvement", name: "Vélo à deux / balade", photo: "https://images.unsplash.com/photo-1775217126598-f78a10208ec5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "En mouvement sur un vélo ou en tandem, complicité captée en action.", technique: "35mm, f/4, suivi AF continu.", focal: [35, 35] },

  // --- COUPLE / Assis / proches
  { cat: "couple", sub: "proches", name: "Assis dos contre un mur/arbre", photo: "https://images.unsplash.com/photo-1771430910761-ba16efc34f13?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Épaule contre épaule ou l'un sur les genoux de l'autre, regard vers l'horizon ou complice entre eux.", technique: "50-85mm, f/2, exploiter la texture du support en arrière-plan flou.", focal: [50, 85] },
  { cat: "couple", sub: "proches", name: "Allongés dans l'herbe", photo: "https://images.unsplash.com/photo-1776266100182-854d83715f98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Vue du dessus ou de profil bas, têtes rapprochées, mains qui se frôlent.", technique: "35mm en plongée ou 85mm au ras du sol, f/2.5.", focal: [35, 85] },
  { cat: "couple", sub: "proches", name: "Sur un banc / marches", photo: "https://images.unsplash.com/photo-1583943349276-61965e599fa5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Corps légèrement tournés l'un vers l'autre plutôt que face caméra, jambes croisées naturellement.", technique: "50-85mm, f/2.2, attention à l'arrière-plan (fuyantes, lignes).", focal: [50, 85] },
  { cat: "couple", sub: "proches", name: "Câlin enveloppant par derrière", photo: "https://images.unsplash.com/photo-1505189014261-0148f9aefa85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "L'un enlace l'autre par derrière, tête posée sur l'épaule, regard vers l'horizon.", technique: "50-85mm, f/2, lumière douce latérale.", focal: [50, 85] },
  { cat: "couple", sub: "proches", name: "Assis au bord de l'eau, pieds dans l'eau", photo: "https://images.unsplash.com/photo-1783283497064-16b8f868b44d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Ambiance détente, jambes dans l'eau, regard complice entre les deux.", technique: "35-50mm, f/2.8, cadrage large pour inclure le décor.", focal: [35, 50] },
  { cat: "couple", sub: "proches", name: "Lecture / moment calme à deux", photo: "https://images.unsplash.com/photo-1758522490426-ae82d2351376?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Posture naturelle, activité partagée (livre, café), capter sans diriger.", technique: "50mm, f/2, lumière ambiante.", focal: [50, 50] },

  // --- COUPLE / Gros plans / détails
  { cat: "couple", sub: "details", name: "Mains entrelacées + bagues", photo: "https://images.unsplash.com/photo-1529519195486-16945f0fb37f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Demander de joindre les mains naturellement, jouer sur les textures (tissu, peau, bijoux).", technique: "85-100mm, f/2, mise au point précise sur la bague ou les jointures.", focal: [85, 100] },
  { cat: "couple", sub: "details", name: "Regard complice, profils face à face", photo: "https://images.unsplash.com/photo-1571771826307-98d0d0999028?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Cadrage très serré sur les deux visages de profil, front proche, léger sourire.", technique: "85mm, f/1.8, mise au point sur les yeux du sujet le plus proche.", focal: [85, 85] },
  { cat: "couple", sub: "details", name: "Nuque / cheveux au vent", photo: "https://images.unsplash.com/photo-1786520995821-c8f6cc25c64c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Photographier de dos ou de 3/4 arrière pendant un mouvement de tête ou de vent.", technique: "85mm, f/2, contre-jour pour souligner les mèches.", focal: [85, 85] },
  { cat: "couple", sub: "details", name: "Doigts qui se frôlent", photo: "https://images.unsplash.com/photo-1698291760176-b95f3f0775d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Gros plan sur les mains qui se rapprochent sans encore se tenir, jouer sur la tension du geste.", technique: "100mm macro, f/2.8, mise au point précise sur les doigts.", focal: [85, 100] },
  { cat: "couple", sub: "details", name: "Alliance sur la main posée sur l'épaule", photo: "https://images.unsplash.com/photo-1612991235474-5ecc873286bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Détail de la bague dans un contexte tactile, main posée sur l'épaule du partenaire.", technique: "85-100mm, f/2, fond flou.", focal: [85, 100] },
  { cat: "couple", sub: "details", name: "Regard direct caméra, profondeur de champ", photo: "https://images.unsplash.com/photo-1752555919235-a1601f7893ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Un des deux visages net face caméra, l'autre flou en amorce au premier plan.", technique: "85mm, f/1.8, mise au point œil AF.", focal: [85, 85] },

  // --- FAMILLE / Groupe multigénérationnel
  { cat: "famille", sub: "multigen", name: "Assis en arc de cercle", photo: "https://images.unsplash.com/photo-1785094342212-27f295b7fd52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Grands-parents assis au centre, enfants/petits-enfants disposés en arc pour éviter l'alignement plat.", technique: "24-35mm, f/5.6-8 pour tout garder net, flash de débouchage en extérieur.", focal: [24, 35] },
  { cat: "famille", sub: "multigen", name: "Marche en famille", photo: "https://images.unsplash.com/photo-1561524891-8e08ab8569f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Faire avancer le groupe vers l'objectif en discutant naturellement, capter les interactions latérales.", technique: "35mm, f/4, rafale, suivi AF continu.", focal: [35, 35] },
  { cat: "famille", sub: "multigen", name: "Câlin collectif", photo: "https://images.unsplash.com/photo-1650523616477-c0b945a43c1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "\"Rapprochez-vous tous et faites un câlin de groupe\" — capter juste après le mouvement de rassemblement.", technique: "24-35mm, f/4, rafale courte.", focal: [24, 35] },
  { cat: "famille", sub: "multigen", name: "Trois générations alignées par taille", photo: "https://images.unsplash.com/photo-1760328249117-18488466e34c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Grands-parents, parents, enfants disposés en dégradé de hauteur plutôt qu'à plat.", technique: "35mm, f/5.6, distance suffisante pour tous les inclure.", focal: [35, 35] },
  { cat: "famille", sub: "multigen", name: "Repas de famille à table", photo: "https://images.unsplash.com/photo-1578496780896-7081cc23c111?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Moment de partage autour d'un repas, capter les échanges naturels sans poser.", technique: "35-50mm, f/2.8, discrétion.", focal: [35, 50] },
  { cat: "famille", sub: "multigen", name: "Jeu de société ou activité commune", photo: "https://images.unsplash.com/photo-1577897113292-3b95936e5206?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Famille regroupée autour d'une activité, capter rires et concentration.", technique: "35-50mm, f/4, lumière ambiante.", focal: [35, 50] },

  // --- FAMILLE / Enfants
  { cat: "famille", sub: "enfants", name: "Jeu / course libre", photo: "https://images.unsplash.com/photo-1690748747428-d5226f2af24d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Laisser l'enfant jouer sans consigne stricte, se mettre à sa hauteur, anticiper les moments de rire.", technique: "35-50mm, vitesse rapide 1/640e, AF continu suivi.", focal: [35, 50] },
  { cat: "famille", sub: "enfants", name: "Portrait au ras du sol", photo: "https://images.unsplash.com/photo-1497881807663-38b9a95b7192?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Se mettre au niveau des yeux de l'enfant, capter un regard direct ou une expression curieuse.", technique: "50-85mm, f/2, mise au point sur l'œil le plus proche.", focal: [50, 85] },
  { cat: "famille", sub: "enfants", name: "Chatouilles / rire éclat", photo: "https://images.unsplash.com/photo-1624272864537-8ecc72b67958?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Demander à un parent de chatouiller doucement l'enfant, rafale au moment du rire.", technique: "35-50mm, f/2.8, rafale haute cadence.", focal: [35, 50] },
  { cat: "famille", sub: "enfants", name: "Portrait avec doudou / objet fétiche", photo: "https://images.unsplash.com/photo-1643078726430-fed25cc73ea3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Enfant tenant son objet préféré, laisser l'expression venir naturellement.", technique: "50-85mm, f/2, mise au point sur les yeux.", focal: [50, 85] },
  { cat: "famille", sub: "enfants", name: "Saut dans les flaques / éclaboussures", photo: "https://images.unsplash.com/photo-1773247290346-1c588e76de3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Action extérieure après la pluie, capter le mouvement de l'eau au moment du saut.", technique: "35-50mm, vitesse 1/1000e mini.", focal: [35, 50] },
  { cat: "famille", sub: "enfants", name: "Endormi / calme, sieste", photo: "https://images.unsplash.com/photo-1517912707202-5dd698d629a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Moment paisible, lumière douce, portrait tout en délicatesse.", technique: "85mm, f/2, lumière de fenêtre tamisée.", focal: [85, 85] },

  // --- FAMILLE / Duo parent-enfant
  { cat: "famille", sub: "parent-enfant", name: "Porté sur les épaules", photo: "https://images.unsplash.com/photo-1605812830455-2fadc55bc4ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Parent porte l'enfant sur les épaules, demander un regard vers le bas ou vers l'horizon ensemble.", technique: "35mm, f/4, léger contre-plongée pour valoriser.", focal: [35, 35] },
  { cat: "famille", sub: "parent-enfant", name: "Front contre front assis", photo: "https://images.unsplash.com/photo-1494451930944-8998635c2123?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Assis face à face ou l'un contre l'autre, moment calme et silencieux à capter.", technique: "50-85mm, f/2, lumière douce latérale.", focal: [50, 85] },
  { cat: "famille", sub: "parent-enfant", name: "Marche main dans la main de dos", photo: "https://images.unsplash.com/photo-1558366361-557c7a4b31b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Les filmer/photographier de dos en train de marcher, insister sur la différence de taille des mains.", technique: "35-50mm, f/4, cadrage bas pour inclure les jambes.", focal: [35, 50] },
  { cat: "famille", sub: "parent-enfant", name: "Bisou sur la joue", photo: "https://images.unsplash.com/photo-1564156280315-1d42b4651629?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Moment tendre spontané, capter juste après le baiser sur la joue.", technique: "85mm, f/2, rafale courte.", focal: [85, 85] },
  { cat: "famille", sub: "parent-enfant", name: "Jeu de bras / porté-tourné", photo: "https://images.unsplash.com/photo-1771785990203-eeecb23ff762?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Le parent fait tourner ou soulève l'enfant en riant, capter le mouvement et l'expression.", technique: "35-50mm, vitesse 1/640e mini.", focal: [35, 50] },
  { cat: "famille", sub: "parent-enfant", name: "Lecture d'une histoire ensemble", photo: "https://images.unsplash.com/photo-1758687126981-417a59c589a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Moment calme, parent et enfant blottis autour d'un livre.", technique: "50-85mm, f/2.2, lumière douce.", focal: [50, 85] },

  // --- FAMILLE / Portraits individuels
  { cat: "famille", sub: "individuel", name: "Portrait 3/4 lumière douce", photo: "https://images.unsplash.com/photo-1617746652908-91e66c07499a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Léger angle de 3/4, menton légèrement baissé, regard vers la lumière la plus douce disponible.", technique: "85mm, f/2, lumière de fenêtre ou ombre extérieure homogène.", focal: [85, 85] },
  { cat: "famille", sub: "individuel", name: "Portrait environnemental", photo: "https://images.unsplash.com/photo-1728706613022-55c1d7559f21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Inclure un élément du lieu (jardin, intérieur familier) pour raconter le contexte de vie.", technique: "35-50mm, f/2.8-4, sujet décentré selon règle des tiers.", focal: [35, 50] },
  { cat: "famille", sub: "individuel", name: "Regard vers l'objectif, sourire naturel", photo: "https://images.unsplash.com/photo-1604072366595-e75dc92d6bdc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Faire parler la personne juste avant le déclenchement (question simple) pour un sourire authentique.", technique: "85mm, f/1.8-2, priorité œil AF.", focal: [85, 85] },
  { cat: "famille", sub: "individuel", name: "Portrait en pied dans son environnement", photo: "https://images.unsplash.com/photo-1781715779302-9d16abf6fd43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Cadrage large corps entier, inclure le décor familier pour raconter le lieu de vie.", technique: "35mm, f/4, sujet décentré selon règle des tiers.", focal: [35, 35] },
  { cat: "famille", sub: "individuel", name: "Portrait de profil contemplatif", photo: "https://images.unsplash.com/photo-1765813135630-5b4fe8396a85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Regard vers l'horizon ou une fenêtre, expression sereine, pas de contact caméra direct.", technique: "85mm, f/2, lumière latérale douce.", focal: [85, 85] },
  { cat: "famille", sub: "individuel", name: "Portrait rire aux éclats", photo: "https://images.unsplash.com/photo-1765560215006-95a3570b07eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400", direction: "Capter un vrai éclat de rire suite à une plaisanterie ou une anecdote.", technique: "85mm, f/1.8, rafale courte.", focal: [85, 85] },

  // --- FAMILLE / Maman avec bébé / enfant
  { cat: "famille", sub: "maman-enfant", name: "Câlin peau à peau avec bébé", photo: "https://images.unsplash.com/photo-1701839640200-ac8c8df193bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman tenant son bébé tout contre elle, câlin tendre, enveloppé dans une couverture douce.", technique: "85mm, f/2, lumière de fenêtre douce, mise au point sur les visages.", focal: [85, 85] },
  { cat: "famille", sub: "maman-enfant", name: "Biberon, moment intime", photo: "https://images.unsplash.com/photo-1652344900727-747b1711de89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman donnant le biberon, regard tourné vers le bébé, cadrage pudique sur les mains/visages.", technique: "50-85mm, f/2.2, lumière douce et enveloppante.", focal: [50, 85] },
  { cat: "famille", sub: "maman-enfant", name: "Bébé porté en écharpe, marche", photo: "https://images.unsplash.com/photo-1647565110523-0f7cb9bddaa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman qui marche avec son bébé porté en écharpe, mouvement naturel, pas de pose figée.", technique: "35-50mm, f/4, suivi AF continu.", focal: [35, 50] },
  { cat: "famille", sub: "maman-enfant", name: "Jeu au sol avec un enfant", photo: "https://images.unsplash.com/photo-1721150643045-69e8fe417f5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman assise au sol en train de jouer avec son enfant, rires partagés, moment spontané.", technique: "35-50mm, f/2.8, se mettre au niveau du sol.", focal: [35, 50] },
  { cat: "famille", sub: "maman-enfant", name: "Bisou sur le front du bébé", photo: "https://images.unsplash.com/photo-1747886804530-7b9b5f2a61f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman qui dépose un bisou sur le front ou la tête du bébé tenu dans ses bras.", technique: "85mm, f/2, mise au point sur le contact des visages.", focal: [85, 85] },
  { cat: "famille", sub: "maman-enfant", name: "Portrait maman et enfant, regards complices", photo: "https://images.unsplash.com/photo-1560707856-3af2ff5ea652?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Maman et enfant assis ensemble, regards l'un vers l'autre, sourire complice.", technique: "50-85mm, f/2, lumière douce latérale.", focal: [50, 85] },

  // --- FAMILLE / Papa avec bébé / enfant
  { cat: "famille", sub: "papa-enfant", name: "Bébé endormi sur le torse", photo: "https://images.unsplash.com/photo-1782946059961-cff3e07c37a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa allongé ou assis, bébé endormi posé sur son torse, moment calme et silencieux.", technique: "50-85mm, f/2, lumière tamisée.", focal: [50, 85] },
  { cat: "famille", sub: "papa-enfant", name: "Porté sur les épaules, enfant qui rit", photo: "https://images.unsplash.com/photo-1768509196702-aa9735b5162e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa qui porte son enfant sur les épaules, tous deux souriants ou riant.", technique: "35mm, f/4, léger contre-plongée pour valoriser.", focal: [35, 35] },
  { cat: "famille", sub: "papa-enfant", name: "Bébé soulevé en l'air, rire", photo: "https://images.unsplash.com/photo-1711391122746-e61d0d46f563?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa qui soulève doucement le bébé en l'air en souriant, bébé qui rit aux éclats.", technique: "35-50mm, vitesse 1/640e mini.", focal: [35, 50] },
  { cat: "famille", sub: "papa-enfant", name: "Marche, enfant à la main et bébé en écharpe", photo: "https://images.unsplash.com/photo-1710167532163-31876e2b1a4c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa qui marche en tenant la main d'un enfant plus grand pendant que le bébé est porté en écharpe.", technique: "35mm, f/4, cadrage large pour inclure toute la scène.", focal: [35, 35] },
  { cat: "famille", sub: "papa-enfant", name: "Biberon donné par le papa", photo: "https://images.unsplash.com/photo-1648743344320-989176fc0184?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa qui donne le biberon au bébé, regard tendre tourné vers lui.", technique: "50-85mm, f/2.2, lumière douce.", focal: [50, 85] },
  { cat: "famille", sub: "papa-enfant", name: "Portrait papa et enfant, front contre front", photo: "https://images.unsplash.com/photo-1717596786112-e08ef20fa535?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Papa et enfant front contre front ou joue contre joue, moment tendre et silencieux.", technique: "85mm, f/2, lumière douce latérale.", focal: [85, 85] },

  // --- CORPORATE / Portraits / trombinoscope
  { cat: "corporate", sub: "trombinoscope", name: "Portrait studio mobile", photo: "https://images.unsplash.com/photo-1612541122840-bf7071c968a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400", direction: "Fond neutre, épaules légèrement de 3/4, regard caméra franc, expression professionnelle mais détendue.", technique: "70-200mm ou 85mm, f/4-5.6, éclairage studio mobile ou lumière de fenêtre diffusée, tethering pour validation directe.", focal: [70, 200] },
  { cat: "corporate", sub: "trombinoscope", name: "Portrait lumière naturelle bureau", photo: "https://images.unsplash.com/photo-1636191284490-fff58f369ec6?w=400", direction: "Positionner la personne face à une fenêtre, éviter les ombres dures, fond dégagé et cohérent avec la charte.", technique: "50-85mm, f/3.5-5, ISO adapté à la lumière ambiante, réflecteur si besoin.", focal: [50, 85] },
  { cat: "corporate", sub: "trombinoscope", name: "Portrait debout bras croisés", photo: "https://images.unsplash.com/photo-1758518727984-17b37f2f0562?w=400", direction: "Position stable, épaules ouvertes, léger sourire, éviter la symétrie parfaite (léger angle du corps).", technique: "70-200mm, f/4, distance suffisante pour compression flatteuse.", focal: [70, 200] },
  { cat: "corporate", sub: "trombinoscope", name: "Portrait assis au bureau", photo: "https://images.unsplash.com/photo-1573496130209-c672e3c309db?w=400", direction: "Assis à son poste de travail, posture ouverte, sourire professionnel détendu.", technique: "70-200mm, f/4, distance pour compression flatteuse.", focal: [70, 200] },
  { cat: "corporate", sub: "trombinoscope", name: "Portrait extérieur devant le bâtiment", photo: "https://images.unsplash.com/photo-1758599543242-31567fb8766e?w=400", direction: "Devant la façade ou le logo de l'entreprise, lumière homogène et fond cohérent.", technique: "50-85mm, f/4, éviter le contre-jour dur.", focal: [50, 85] },
  { cat: "corporate", sub: "trombinoscope", name: "Série d'expressions variées", photo: "https://images.unsplash.com/photo-1758691737605-69a0e78bd193?w=400", direction: "Plusieurs prises (souriant, neutre, dynamique) pour laisser le choix à la personne et au service com.", technique: "85mm, f/4, tethering pour validation en direct.", focal: [85, 85] },

  // --- CORPORATE / Ambiance travail / atelier
  { cat: "corporate", sub: "atelier", name: "Geste technique en action", photo: "https://images.unsplash.com/photo-1660796334938-cf0b03be7e6d?w=400", direction: "Demander de reproduire un geste métier habituel sans regarder l'objectif, se placer pour capter les mains et le visage concentré.", technique: "24-70mm, f/2.8-4, gérer les sources de lumière mixtes (néons + naturelle).", focal: [24, 70] },
  { cat: "corporate", sub: "atelier", name: "Plan large de l'environnement", photo: "https://images.unsplash.com/photo-1676018366904-c083ed678e60?w=400", direction: "Montrer le poste de travail ou l'atelier dans son ensemble, personne active en second plan.", technique: "16-24mm, f/5.6-8 pour la profondeur de champ, trépied si lumière faible.", focal: [16, 24] },
  { cat: "corporate", sub: "atelier", name: "Détail outil / matière", photo: "https://images.unsplash.com/photo-1626252685663-64c6bf60afb1?w=400", direction: "Gros plan sur un outil, un matériau ou un produit fini, en lien avec le métier représenté.", technique: "50-100mm macro si possible, f/4, lumière dirigée pour révéler la texture.", focal: [50, 100] },
  { cat: "corporate", sub: "atelier", name: "Échange entre collègues sur un poste de travail", photo: "https://images.unsplash.com/photo-1671726203393-f1a957014635?w=400", direction: "Moment d'entraide ou d'explication, capter la concentration naturelle des deux personnes.", technique: "35-50mm, f/2.8, discrétion.", focal: [35, 50] },
  { cat: "corporate", sub: "atelier", name: "Manipulation de machine / outil spécifique", photo: "https://images.unsplash.com/photo-1598299803204-b73796f43289?w=400", direction: "Focus sur le geste précis et sécurisé, mains et outil au premier plan.", technique: "24-70mm, f/4, gérer les sources de lumière mixtes.", focal: [24, 70] },
  { cat: "corporate", sub: "atelier", name: "Contrôle qualité / finition produit", photo: "https://images.unsplash.com/photo-1700727448575-6f1680cd7d75?w=400", direction: "Moment d'inspection minutieuse, expression concentrée, produit bien visible.", technique: "50-85mm, f/2.8, lumière dirigée.", focal: [50, 85] },

  // --- CORPORATE / Groupe équipe
  { cat: "corporate", sub: "equipe", name: "Groupe debout dynamique", photo: "https://images.unsplash.com/photo-1676694047732-768cea5b66eb?w=400", direction: "Disposer en quinconce (pas alignés), demander un léger mouvement (bras croisés variés, une personne qui rit) pour casser la rigidité.", technique: "24-35mm, f/5.6-8, flash de débouchage si besoin, plusieurs déclenchements pour éviter les yeux fermés.", focal: [24, 35] },
  { cat: "corporate", sub: "equipe", name: "Équipe en réunion / brainstorm", photo: "https://images.unsplash.com/photo-1758873271687-ec6b5bc28fe8?w=400", direction: "Capter un moment d'échange réel autour d'une table, éviter les regards caméra forcés.", technique: "35-50mm, f/2.8, discrétion, lumière ambiante privilégiée.", focal: [35, 50] },
  { cat: "corporate", sub: "equipe", name: "Marche groupée couloir/extérieur", photo: "https://images.unsplash.com/photo-1758691736995-fd7222612210?w=400", direction: "Faire avancer le groupe vers l'objectif en discutant, capter dynamisme et cohésion.", technique: "35mm, f/4, rafale, suivi AF continu.", focal: [35, 35] },
  { cat: "corporate", sub: "equipe", name: "Équipe autour d'un écran / projet", photo: "https://images.unsplash.com/photo-1758873268695-1b55590e507a?w=400", direction: "Collaboration devant un ordinateur ou un tableau, capter le dynamisme naturel de l'échange.", technique: "35mm, f/2.8, discrétion.", focal: [35, 35] },
  { cat: "corporate", sub: "equipe", name: "Pause café d'équipe", photo: "https://images.unsplash.com/photo-1783780933161-15c313c1eff1?w=400", direction: "Moment convivial informel, rires autour d'un café, ambiance décontractée.", technique: "35-50mm, f/2.8, lumière ambiante.", focal: [35, 50] },
  { cat: "corporate", sub: "equipe", name: "Groupe assis sur des marches/gradins", photo: "https://images.unsplash.com/photo-1759744428323-348de7ba68a1?w=400", direction: "Disposition originale (assis à différents niveaux) pour une photo d'équipe décontractée.", technique: "24-35mm, f/5.6, plusieurs déclenchements.", focal: [24, 35] },

  // --- CORPORATE / Networking
  { cat: "corporate", sub: "networking", name: "Poignée de main", photo: "https://images.unsplash.com/photo-1758599543152-a73184816eba?w=400", direction: "Se placer légèrement de côté au moment du contact, viser les deux visages et la poignée de main nette.", technique: "50-70mm, f/4, rafale courte au moment du contact.", focal: [50, 70] },
  { cat: "corporate", sub: "networking", name: "Échange de cartes / discussion debout", photo: "https://images.unsplash.com/photo-1785140629551-4f257c100241?w=400", direction: "Rester discret en retrait, privilégier les instants d'écoute active (hochement de tête, sourire).", technique: "70-200mm, f/2.8-4, discrétion maximale.", focal: [70, 200] },
  { cat: "corporate", sub: "networking", name: "Prise de parole / intervention", photo: "https://images.unsplash.com/photo-1544531586-fde5298cdd40?w=400", direction: "Se placer face ou légèrement de côté par rapport à l'intervenant, anticiper les gestes marquants.", technique: "70-200mm, f/2.8, vitesse 1/250e mini, ISO élevé si salle sombre.", focal: [70, 200] },
  { cat: "corporate", sub: "networking", name: "Groupe en discussion, verre à la main", photo: "https://images.unsplash.com/photo-1644446608979-45eb5c2fbbe3?w=400", direction: "Ambiance cocktail professionnel, échanges informels entre plusieurs personnes.", technique: "50-70mm, f/2.8, discrétion.", focal: [50, 70] },
  { cat: "corporate", sub: "networking", name: "Remise de récompense / trophée", photo: "https://images.unsplash.com/photo-1659080907377-ee6a57fb6b9c?w=400", direction: "Moment officiel, poignée de main et sourire franc face caméra.", technique: "50-85mm, f/4, rafale au moment du geste.", focal: [50, 85] },
  { cat: "corporate", sub: "networking", name: "Table ronde / panel de discussion", photo: "https://images.unsplash.com/photo-1769798643630-194a0fcfa367?w=400", direction: "Plusieurs intervenants assis, capter les interactions et les regards échangés.", technique: "70-200mm, f/2.8, ISO élevé si besoin.", focal: [70, 200] },

  // --- PERSONNE SEULE / Femme
  { cat: "solo", sub: "femme", name: "Portrait regard caméra, lumière naturelle", photo: "https://images.unsplash.com/photo-1762552280779-020f19edd6cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Proche d'une fenêtre, regard direct et assuré vers l'objectif.", technique: "85mm, f/1.8, lumière de fenêtre douce.", focal: [85, 85] },
  { cat: "solo", sub: "femme", name: "Marche en mouvement, cheveux qui bougent", photo: "https://images.unsplash.com/photo-1688607929670-0c150d3d3cd4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Captée en mouvement latéral, cheveux ou tissu en mouvement, expression naturelle.", technique: "50-85mm, vitesse 1/500e mini.", focal: [50, 85] },
  { cat: "solo", sub: "femme", name: "Pose assise, jambes croisées, regard vers le bas", photo: "https://images.unsplash.com/photo-1707303051965-bb814c443aa1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Ambiance douce et posée, lumière tamisée, expression pensive.", technique: "85mm, f/2, lumière douce diffuse.", focal: [85, 85] },
  { cat: "solo", sub: "femme", name: "Portrait noir et blanc, expression forte", photo: "https://images.unsplash.com/photo-1540172777610-b15b605dd68d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Portrait de femme seule, expression intense et déterminée, contraste marqué façon noir et blanc.", technique: "85mm, f/2, lumière dure ou latérale pour accentuer le relief du visage.", focal: [85, 85] },
  { cat: "solo", sub: "femme", name: "Debout contre un mur, jambe repliée", photo: "https://images.unsplash.com/photo-1636696860462-777d41950151?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Femme seule debout de profil ou 3/4, appuyée contre un mur, une jambe repliée, pose décontractée.", technique: "50-85mm, f/2.8, fond texturé (mur, façade).", focal: [50, 85] },
  { cat: "solo", sub: "femme", name: "Rire spontané, tête renversée en arrière", photo: "https://images.unsplash.com/photo-1496360711189-5edeb09fe715?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Femme seule qui rit aux éclats, tête légèrement renversée en arrière, énergie et joie.", technique: "85mm, f/1.8, rafale courte pour capter le mouvement.", focal: [85, 85] },

  // --- PERSONNE SEULE / Homme
  { cat: "solo", sub: "homme", name: "Portrait 3/4 bras croisés, regard confiant", photo: "https://images.unsplash.com/photo-1678282342910-a135f7b900ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Posture stable, épaules ouvertes, regard direct et déterminé.", technique: "85mm, f/2, lumière latérale.", focal: [85, 85] },
  { cat: "solo", sub: "homme", name: "En mouvement, veste sur l'épaule", photo: "https://images.unsplash.com/photo-1602795187914-00e35334033b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Marche décontractée, geste naturel, veste tenue par un doigt sur l'épaule.", technique: "35-50mm, f/2.8, suivi AF continu.", focal: [35, 50] },
  { cat: "solo", sub: "homme", name: "Portrait assis, mains jointes, réflexion", photo: "https://images.unsplash.com/photo-1530071698688-1e4c30e1ea52?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Ambiance posée, regard pensif vers le bas ou le côté, mains jointes devant soi.", technique: "85mm, f/2, lumière douce.", focal: [85, 85] },
  { cat: "solo", sub: "homme", name: "Portrait en contre-plongée, posture forte", photo: "https://images.unsplash.com/photo-1723228451449-f8f0866a82b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Homme seul photographié en légère contre-plongée, posture droite, regard déterminé vers l'horizon.", technique: "50-85mm, f/2.8, angle bas pour valoriser la stature.", focal: [50, 85] },
  { cat: "solo", sub: "homme", name: "Adossé à un mur, mains dans les poches", photo: "https://images.unsplash.com/photo-1770979820036-300fa34c693d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Homme seul adossé à un mur ou une surface texturée, mains dans les poches, regard vers la caméra ou de côté.", technique: "50-85mm, f/2.8, fond simple et texturé.", focal: [50, 85] },
  { cat: "solo", sub: "homme", name: "Rire naturel, regard de côté", photo: "https://images.unsplash.com/photo-1775757231072-30700ffb7e7b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400", direction: "Homme seul qui rit naturellement, regard légèrement de côté, expression détendue et spontanée.", technique: "85mm, f/1.8, rafale courte.", focal: [85, 85] }
];

// Objectifs courants proposés dans "Mon matériel" (Victor peut aussi ajouter les siens).
const LENS_PRESETS = [
  { id: "1635", label: "16-35mm f/2.8", minMM: 16, maxMM: 35 },
  { id: "2470", label: "24-70mm f/2.8", minMM: 24, maxMM: 70 },
  { id: "70200", label: "70-200mm f/2.8", minMM: 70, maxMM: 200 },
  { id: "35fixe", label: "35mm f/1.4 ou f/1.8", minMM: 35, maxMM: 35 },
  { id: "50fixe", label: "50mm f/1.2 ou f/1.8", minMM: 50, maxMM: 50 },
  { id: "85fixe", label: "85mm f/1.2 ou f/1.8", minMM: 85, maxMM: 85 },
  { id: "macro100", label: "100mm macro", minMM: 100, maxMM: 100 }
];
